### ISSUE TITLE
Difference to pyftsubset?

### ISSUE THREAD

**Issue by madig** [source-foundry/dehinter#5]
```
$ pyftsubset --help
[...]
Hinting options:
  --hinting
      Keep hinting [default]
  --no-hinting
      Drop glyph-specific hinting and font-wide hinting tables, as well
      as remove hinting-related bits and pieces from other tables (eg. GPOS).
      See --hinting-tables for list of tables that are dropped by default.
      Instructions and hints are stripped from 'glyf' and 'CFF ' tables
      respectively. This produces (sometimes up to 30%) smaller fonts that
      are suitable for extremely high-resolution systems, like high-end
      mobile devices and retina displays.
[...]
```

**Comment by chrissimpkins** [comment]
hmmm. Did not know that this feature existed in the tool.  Too late now :)

Will take a look.

**Comment by chrissimpkins** [comment]
With default execution of pyftsubset using:

```
$ pyftsubset  Ubuntu-Regular.ttf --glyphs="*" --no-hinting
```

vs. dehinter with:

```
$ dehinter Ubuntu-Regular.ttf
```

I get a very large diff.  pyftsubset appears to change glyph names, remove post table values, remove nameID records, and more by default.  The docs state that that it performs optimizations in preparation for use in web font compiles.  There is none of that in this project.  This simply removes glyf table TrueType instruction set assembly and "hinting associated" tables.  The latter is broadly defined and follows the approach used during the execution of `ttfautohint -d [FONT]`.  

I am also clearing bit 4 of the head table flags when LTSH and hdmx tables are removed which according to my read of the OT spec appears to follow guidance.  Based on n=1 testing with pyftsubset I don't think that is happening.  Likely a minor Microsoft only issue?  I still need to add the source for VDMX table removals (#3) which will be in the next release.  Once that is in place this project is *nearly* a reverse engineered `ttfautohint -d` in Python.  There are a handful of head table flags bits outside of the bit 4 issue that are not perfect matches to what takes place with `ttfautohint -d` execution but otherwise there is a clean diff across a number of fonts that I've tested.  Need to investigate further...

**Comment by anthrotype** [comment]
FYI, the `table__g_l_y_f` class has a `removeHinting` method, which the subsetter is also using. I recommend you do the same
https://github.com/fonttools/fonttools/blob/197b36fef4a71fa967cb81ec20a63de1f34b6fd7/Lib/fontTools/ttLib/tables/_g_l_y_f.py#L1161
